namespace: birthday

app:
  image:
    repository: piowisni/birthday-tekken-api
    tag: latest
    pullPolicy: Always
  resources:
    limits:
      cpu: "2"
      memory: "2Gi"
    requests:
      cpu: "1"
      memory: "1Gi"

service:
  type: ClusterIP
  port: 8080

postgresql:
  enabled: true
  image: postgres:16-alpine
  username: postgres
  password: changeme
  database: birthdaydb
  storage: 2Gi
  resources:
    limits:
      cpu: "500m"
      memory: "1Gi"
    requests:
      cpu: "100m"
      memory: "768Mi"
      
ingress:
  enabled: true
  className: nginx
  host: birthday.192.168.49.2.sslip.io
  path: /
  pathType: Prefix
  annotations: {}

rabbitmq:
  username: appuser
  password: apppass
  vhost: "/"
  resources:
    requests:
      cpu: "50m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"


createNamespace: false
