apiVersion: v1
kind: Service
metadata:
  name: {{ include "birthday-tekken-api.name" . }}   # => birthday-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "birthday-tekken-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app: {{ include "birthday-tekken-api.name" . }}  # musi = label w Podzie
  ports:
    - name: http
      port: {{ .Values.service.port | default 8080 }}  # na to wskazuje Ingress
      targetPort: 8080                                  # NUMER (odporne na zmianę nazwy portu w Podzie)
