{{- if and .Values.istio.enabled .Values.istio.destinationRule.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: birthday-api
  namespace: {{ .Values.namespace }}
spec:
  host: birthday-api.{{ .Values.namespace }}.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  {{- end }}
